class Text:
    # Design = List Int
    # dictionary = Dict Char Design
    dictionary = {
        'a': [" o ",
              "o o",
              "ooo",
              "o o",
              "o o"],
        'b': ["oo ",
              "o o",
              "oo ",
              "o o",
              "oo "],
        'c': [" oo",
              "o  ",
              "o  ",
              "o  ",
              " oo"],
        'd': ["oo ",
              "o o",
              "o o",
              "o o",
              "oo "],
        'e': ["oo",
              "o ",
              "oo",
              "o ",
              "oo"],
        'f': ["oo",
              "o ",
              "oo",
              "o ",
              "o "],
        'g': [" ooo",
              "o  ",
              "o oo",
              "o  o",
              " oo "],
        'h': ["o o",
              "o o",
              "ooo",
              "o o",
              "o o"],
        'i': ["o",
              "o",
              "o",
              "o",
              "o"],
        'j': ["  o",
              "  o",
              "  o",
              "o o",
              " o"],
        'k': ["o  o",
              "o o ",
              "oo  ",
              "o o ",
              "o  o"],
        'l': ["o ",
              "o ",
              "o ",
              "o ",
              "oo"],
        'm': ["o   o",
              "oo oo",
              "o o o",
              "o   o",
              "o   o"],
        'n': ["o   o",
              "oo  o",
              "o o o",
              "o  oo",
              "o   o"],
        'o': [" oo ",
              "o  o",
              "o  o",
              "o  o",
              " oo "],
        'p': ["oo ",
              "o o",
              "oo ",
              "o  ",
              "o  "],
        'q': [" oo",
              "o o",
              " oo",
              "  o",
              "  o"],
        'r': ["oo ",
              "o o",
              "oo ",
              "o o",
              "o o"],
        's': [" oo",
              "o  ",
              " oo",
              "  o",
              "oo "],
        't': ["ooo",
              " o ",
              " o ",
              " o ",
              " o "],
        'u': ["o o",
              "o o",
              "o o",
              "o o",
              "ooo"],
        'v': ["o o",
              "o o",
              "o o",
              "o o",
              " o "],
        'w': ["o   o",
              "o o o",
              "o o o",
              "oo oo",
              "o   o"],
        'x': ["o o",
              "o o",
              " o ",
              "o o",
              "o o"],
        'y': ["o o",
              "o o",
              " o ",
              " o ",
              " o "],
        'z': ["ooo",
              "  o",
              " o ",
              "o  ",
              "ooo"],
        '0': [" o ",
              "o o",
              "o o",
              "o o",
              " o "],
        '1': ["o",
              "o",
              "o",
              "o",
              "o"],
        '2': [" o ",
              "o o",
              "  o",
              " o ",
              "ooo"],
        '3': ["ooo",
              "  o",
              " oo",
              "  o",
              "oo "],
        '4': ["o o",
              "o o",
              "ooo",
              "  o",
              "  o"],
        '5': ["ooo",
              "o  ",
              "oo ",
              "  o",
              "oo "],
        '6': ["o  ",
              "o  ",
              "ooo",
              "o o",
              "ooo"],
        '7': ["ooo",
              "  o",
              "  o",
              "  o",
              "  o"],
        '8': ["ooo",
              "o o",
              "ooo",
              "o o",
              "ooo"],
        '9': ["ooo",
              "o o",
              "ooo",
              "  o",
              "ooo"],
        ' ': [" ",
              " ",
              " ",
              " ",
              " "],
        '.': [" ",
              " ",
              " ",
              " ",
              "o"],
        ':': [" ",
              "o",
              " ",
              " ",
              "o"],
        '=': ["   ",
              "ooo",
              "   ",
              "ooo",
              "   "],
        ',': ["  ",
              "  ",
              "  ",
              " o",
              "o "],
        '-': ["  ",
              "  ",
              "oo",
              "  ",
              "  "],
        '[': ["oo",
              "o ",
              "o ",
              "o ",
              "oo"],
        ']': ["oo",
              " o",
              " o",
              " o",
              "oo"]
    }

    def __init__(self):
        self.letters = {char: Text.__design_to_letter(design) for char, design in Text.dictionary.items()}

    def string_to_letters(self, string):
        return [self.letters.get(char) for char in string.lower() if self.letters.get(char)]

    @staticmethod
    def __get_width(design):
        return max([len(line) for line in design])

    @staticmethod
    def __get_positions(design):
        positions = []
        for y, line in enumerate(design):
            for x, char in enumerate(line):
                if char is not ' ':
                    positions.append({
                        'x': x,
                        'y': y
                    })
        return positions

    @staticmethod
    def __design_to_letter(design):
        return {
            'width': Text.__get_width(design),
            'positions': Text.__get_positions(design)
        }

